import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('C:/Users/Nandika/Downloads/best_selling_books_2.csv')
print("Shape:",df.shape)
print(df.head())
print(df.columns)
df['Volume Sales'] = df['Volume Sales'].astype(str).str.replace(',','').astype(int)
df['Genre'] = df['Genre'].str.strip()
df['Author'] = df['Author'].str.strip()
total_sales = df['Volume Sales'].sum()
print(f"Total Volume Sales: {total_sales:,}")
Top_authors = df.groupby('Author')['Volume Sales'].sum().sort_values(ascending=False).head(10)
print("\nTop 10 best selling authors by volume sales:")
print(Top_authors)
top_genres = df.groupby('Genre')['Volume Sales'].sum().sort_values(ascending=False).head(10)
print("\nTop 10 Best-Selling Genres by Volume Sales:")
print(top_genres)
plt.figure(figsize=(12,7))
Top_authors.plot(kind='bar',color='Red')
plt.title('Top 10 best selling authors by volume sales', fontsize=16)
plt.xlabel('Author',fontsize=12)
plt.ylabel('Total Volume sales (in millions)', fontsize=12)
plt.xticks(rotation=45,ha='right', fontsize=10)
plt.grid(axis='y',linestyle='--', alpha=0.7)
plt.tight_layout()
plt.figure(figsize=(10,10))
top_genres.plot(kind='pie',autopct='%1.1f%%',startangle=90,colors=plt.cm.Paired.colors)
plt.title('Percentage of volume sales by Top 10 genres',fontsize='16')
plt.ylabel('')
plt.tight_layout()
plt.figure(figsize=(10, 6))
plt.hist(df['Volume Sales'], bins=20, color='lightgreen', edgecolor='black')
plt.title('Distribution of Volume Sales', fontsize=16)
plt.xlabel('Volume Sales', fontsize=12)
plt.ylabel('Number of Books', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()
plt.figure(figsize=(8, 5))
plt.boxplot(df['Volume Sales'], vert=False)
plt.title('Box Plot of Volume Sales', fontsize=16)
plt.xlabel('Volume Sales', fontsize=12)
plt.tight_layout()
plt.show()
plt.show()
